config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "sessions#new"
    as :user do
      get "/signup", to: "devise/sessions#new"
      post "/signup", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
    end
    scope module: :supervisor do
      resources :questions
      as :questions do
        get "/new_list_questions", to: "questions#new_list"
        post "/create_list_questions", to: "questions#create_list"
      end
      resources :exams
      resources :trainees do
        resources :user_exams
      end
      resources :users do
        collection do
          get "/trainees", to: "users#trainees_index"
          get "/supervisors", to: "users#supervisors_index"
        end
      end
    end
    scope module: :trainee do
      resources :user_exams
    end
    devise_for :users
  end
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :subject
  scope :sort_by_created_at_desc, ->{order(created_at: :desc)}
  has_many :exam_questions, dependent: :destroy
  has_many :questions, through: :exam_questions
  has_many :user_exams, dependent: :destroy
  scope :questions_sort_by_created_at_asc, (lambda do |exam|
    exam.questions.order(created_at: :asc)
  end)
  delegate :name, to: :subject, prefix: true
end

app/controllers/supervisor/exams_controller.rb
class Supervisor::ExamsController < SupervisorController
  before_action :load_exam, only: :show
  load_and_authorize_resource

  def index
    @q = Exam.ransack(params[:q])
    @exams = @q.result.includes(:subject)
               .paginate(page: params[:page]).per_page(Settings.page)
  end

  def show
    @questions = Exam.questions_sort_by_created_at_asc(@exam).includes(:answers)
  end

  private

  def load_exam
    @exam = Exam.find_by(id: params[:id])
    return if @exam

    flash[:danger] = t("exams.not_found!")
    redirect_back(fallback_location: supervisor_exams_path)
  end
end

app/controllers/supervisor/questions_controller.rb
class Supervisor::QuestionsController < SupervisorController
  before_action :load_subject, :load_file_param, :correct_file_type,
                only: :create_list
  load_and_authorize_resource

  def index
    @questions = @questions.sort_by_created_at_desc
                           .paginate(page: params[:page])
                           .per_page(Settings.page)
  end

  def new_list
    @subjects = Subject.sort_by_created_at_desc
  end

  def create_list
    FileService.read_questions_from_file!(@file_path, @subject)
    flash[:success] = t "questions.create_list_success"
    redirect_to questions_path
  rescue ActiveRecord::ActiveRecordError
    flash[:danger] = t "questions.create_list_fail"
    redirect_to new_list_questions_path
  end

  private

  def load_subject
    @subject = Subject.find_by id: params[:subject].to_i
    return if @subject

    flash[:danger] = t "questions.choice_subject!"
    redirect_to new_list_questions_path
  end

  def load_file_param
    @file_param = params["file"]
    return if @file_param

    flash[:danger] = t "questions.please_choice_file!"
    redirect_to new_list_questions_path
  end

  def correct_file_type
    @file_path = @file_param.tempfile.to_path.to_s
    return if @file_path.end_with?(".xlsx") || @file_path.end_with?(".xls")

    flash[:danger] = t "questions.please_choice_correct_file_type!"
    redirect_to new_list_questions_path
  end
end

app/controllers/supervisor/user_exams_controller.rb
class Supervisor::UserExamsController < SupervisorController
  before_action :load_trainee, only: :index
  authorize_resource

  def index
    @user_exams = @trainee.user_exams
                          .sort_by_created_at_desc
                          .includes({exam: :exam_questions}, :subject)
                          .paginate(page: params[:page])
                          .per_page(Settings.page)
  end

  private

  def load_trainee
    @trainee = User.find_by id: params[:trainee_id]
    return if @trainee

    flash[:danger] = t "trainees.not_found!"
    redirect_to root_path
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < SupervisorController
  authorize_resource

  def trainees_index
    @q = User.ransack(params[:q])
    @trainees = @q.result.trainee.sort_by_created_at_desc
                  .includes(:user_exams)
                  .page(params[:page]).per_page(Settings.page)
  end

  def supervisors_index
    @q = User.ransack(params[:q])
    @supervisors = @q.result.supervisor.sort_by_created_at_desc
                     .page(params[:page]).per_page(Settings.page)
  end
end

app/controllers/supervisor_controller.rb
class SupervisorController < ApplicationController
  before_action :authenticate_user!

  private

  def current_ability
    @current_ability ||=
      Ability.new(current_user, Settings.namespace.supervisor)
  end
end

app/views/supervisor/exams/_exam.html.erb
<tr>
  <td><%= exam.name %></td>
  <td><%= exam.subject_name %></td>
  <td><%= l(exam.created_at, format: :long) %></td>
  <td><%= exam.time %></td>
  <td><%= exam.total_number_questions %></td>
  <td>
      <%= link_to t("exams.info"), exam_path(exam), class: "btn btn-primary", role: "button" %>
  </td>
  <td>
      <%= link_to t("exams.edit"), "#", class: "btn btn-success", role: "button" %>
  </td>
  <td>
      <%= link_to t("exams.delete"), "#", method: :delete, class: "btn btn-danger", role: "button" %>
  </td>
</tr>

app/views/supervisor/exams/_exam_question.html.erb
<li class="exam-questions">
  <%= question.content %>
  <ol class="exam-question-answers">
    <% question.answers.each do |answer| %>
      <li class=<%= answer.correct? ? "correct" : "non-correct" %>><%= answer.content %></li>
    <% end %>
  </ol>
  <div class="buttons-container">
    <%= link_to t("questions.info"), "#", class: "btn btn-primary" %>
    <%= link_to t("questions.edit"), "#", class: "btn btn-success" %>
    <%= link_to t("questions.delete"), "#", method: :delete, class: "btn btn-danger" %>
  </div>
</li>

app/views/supervisor/exams/index.html.erb
<% provide :title, t("exams.title.all") %>
<h1><%= t("exams.title.all") %></h1>
<div class="row">
  <%= search_form_for @q, class: "input-group search-box" do |f| %>
    <%= f.text_field :name_or_subject_name_cont, class: "form-control", placeholder: t("exams.search_for") %>
    <span class="input-group-btn">
      <%= f.submit t("exams.search"), class: "btn btn-default" %>
    </span>
  <% end %>
</div>
<div class="exam-container">
  <table class="table">
    <thead>
      <tr>
        <th class="exam_name">
          <%= sort_link(@q, :name) do %>
            <strong>
              <%= t("exams.name") %>
            </strong>
          <% end %>
        </th>
        <th class="exam_subject">
          <%= sort_link(@q, :subject_id) do %>
            <strong>
              <%= t("exams.subject") %>
            </strong>
          <% end %>
        </th>
        <th class="exam_create_time">
          <%= sort_link(@q, :created_at) do %>
            <strong>
              <%= t("exams.create_time") %>
            </strong>
          <% end %>
        </th>
        <th class="exam_duration">
          <%= sort_link(@q, :time) do %>
            <strong>
              <%= t("exams.duration") %>
            </strong>
          <% end %>
        </th>
        <th class="exam_question_number">
          <%= sort_link(@q, :total_number_questions) do %>
            <strong>
              <%= t("exams.total_questions") %>
            </strong>
          <% end %>
        </th>
        <th class="exam_view"><%= t("exams.view") %></th>
        <th class="exam_edit"><%= t("exams.edit") %></th>
        <th class="exam_delete"><%= t("exams.delete") %></th>
      </tr>
    </thead>
    <%= render(@exams) || t("exams.no_result_was_found_html") %>
  </table>
  <div class="pagination-container">
    <%= will_paginate @collection, previous_label: t("previous"), next_label: t("next")%>
  </div>
</div>

app/views/supervisor/exams/show.html.erb
<% provide :title, t("exams.title.detail") %>
<h1><%= t("exams.title.detail") %></h1>
<div class="row">
  <div class="input-group search-box">
    <input type="text" class="form-control" placeholder="<%= t("questions.search_for") %>">
    <span class="input-group-btn">
      <button class="btn btn-default" type="button">
        <%= t("questions.search") %>
      </button>
    </span>
  </div>
</div>
<div class="question-container">
  <ol class="exam-questions-list">
    <%= render partial: "exam_question", collection: @questions, as: :question %>
  </ol>
</div>