config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "sessions#new"
    as :user do
      get "/signup", to: "devise/sessions#new"
      post "/signup", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
    end
    scope module: :supervisor do
      resources :questions
      as :questions do
        get "/new_list_questions", to: "questions#new_list"
        post "/create_list_questions", to: "questions#create_list"
      end
      resources :exams
      resources :trainees do
        resources :user_exams
      end
      resources :users do
        collection do
          get "/trainees", to: "users#trainees_index"
          get "/supervisors", to: "users#supervisors_index"
        end
      end
    end
    scope module: :trainee do
      resources :user_exams
    end
    devise_for :users
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject
  has_many :answers, dependent: :destroy
  enum choice_type: {single: 1, multiple: 2}
  scope :sort_by_created_at_desc, ->{order(created_at: :desc)}
  validates :content, presence: true,
            length: {maximum: Settings.question.content.max_length}
  validates :choice_type, presence: true
end

app/controllers/supervisor/exams_controller.rb
class Supervisor::ExamsController < SupervisorController
  before_action :load_exam, only: :show
  load_and_authorize_resource

  def index
    @q = Exam.ransack(params[:q])
    @exams = @q.result.includes(:subject)
               .paginate(page: params[:page]).per_page(Settings.page)
  end

  def show
    @questions = Exam.questions_sort_by_created_at_asc(@exam).includes(:answers)
  end

  private

  def load_exam
    @exam = Exam.find_by(id: params[:id])
    return if @exam

    flash[:danger] = t("exams.not_found!")
    redirect_back(fallback_location: supervisor_exams_path)
  end
end

app/controllers/supervisor/questions_controller.rb
class Supervisor::QuestionsController < SupervisorController
  before_action :load_subject, :load_file_param, :correct_file_type,
                only: :create_list
  load_and_authorize_resource

  def index
    @questions = @questions.sort_by_created_at_desc
                           .paginate(page: params[:page])
                           .per_page(Settings.page)
  end

  def new_list
    @subjects = Subject.sort_by_created_at_desc
  end

  def create_list
    FileService.read_questions_from_file!(@file_path, @subject)
    flash[:success] = t "questions.create_list_success"
    redirect_to questions_path
  rescue ActiveRecord::ActiveRecordError
    flash[:danger] = t "questions.create_list_fail"
    redirect_to new_list_questions_path
  end

  private

  def load_subject
    @subject = Subject.find_by id: params[:subject].to_i
    return if @subject

    flash[:danger] = t "questions.choice_subject!"
    redirect_to new_list_questions_path
  end

  def load_file_param
    @file_param = params["file"]
    return if @file_param

    flash[:danger] = t "questions.please_choice_file!"
    redirect_to new_list_questions_path
  end

  def correct_file_type
    @file_path = @file_param.tempfile.to_path.to_s
    return if @file_path.end_with?(".xlsx") || @file_path.end_with?(".xls")

    flash[:danger] = t "questions.please_choice_correct_file_type!"
    redirect_to new_list_questions_path
  end
end

app/controllers/supervisor/user_exams_controller.rb
class Supervisor::UserExamsController < SupervisorController
  before_action :load_trainee, only: :index
  authorize_resource

  def index
    @user_exams = @trainee.user_exams
                          .sort_by_created_at_desc
                          .includes({exam: :exam_questions}, :subject)
                          .paginate(page: params[:page])
                          .per_page(Settings.page)
  end

  private

  def load_trainee
    @trainee = User.find_by id: params[:trainee_id]
    return if @trainee

    flash[:danger] = t "trainees.not_found!"
    redirect_to root_path
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < SupervisorController
  authorize_resource

  def trainees_index
    @q = User.ransack(params[:q])
    @trainees = @q.result.trainee.sort_by_created_at_desc
                  .includes(:user_exams)
                  .page(params[:page]).per_page(Settings.page)
  end

  def supervisors_index
    @q = User.ransack(params[:q])
    @supervisors = @q.result.supervisor.sort_by_created_at_desc
                     .page(params[:page]).per_page(Settings.page)
  end
end

app/controllers/supervisor_controller.rb
class SupervisorController < ApplicationController
  before_action :authenticate_user!

  private

  def current_ability
    @current_ability ||=
      Ability.new(current_user, Settings.namespace.supervisor)
  end
end

app/views/supervisor/questions/_question.html.erb
<li class="questions">
  <%= question.content %>
  <div class="buttons-container">
    <%= link_to t("questions.info"), "#", class: "btn btn-primary" %>
    <%= link_to t("questions.edit"), "#", class: "btn btn-success" %>
    <%= link_to t("questions.delete"), "#", method: :delete, class: "btn btn-danger" %>
  </div>
</li>

app/views/supervisor/questions/index.html.erb
<%= javascript_pack_tag "questions" %>
<div>
  <%= link_to new_list_questions_path, class: "btn btn-primary button" do %>
    <%= t("questions.create_list_questions") %>&nbsp;&nbsp;<i class="glyphicon glyphicon-plus"></i>
  <% end %>
</div>
<% provide :title, t("questions.title.all") %>
<h1><%= t("questions.title.all") %></h1>
<div class="row">
  <div class="input-group search-box">
    <input type="text" class="form-control" placeholder="<%= t("questions.search_for") %>">
    <span class="input-group-btn">
      <button class="btn btn-default" type="button">
        <%= t("questions.search") %>
      </button>
    </span>
  </div>
</div>
<div class="question-container">
  <ol class="quiz">
    <%= render(@questions) || t("questions.no_result_was_found_html") %>
  </ol>
  <div class="pagination-container">
    <%= will_paginate @collection, previous_label: t("previous"), next_label: t("next")%>
  </div>
</div>

app/views/supervisor/questions/new_list.html.erb
<% provide :title, t("questions.title.create_list_questions") %>

<h1><%= t("questions.title.create_list_questions") %></h1>
<div class="row new-list-questions">
  <%= form_for :list_questions, url: create_list_questions_path, html: { multipart: true }, class:"form-control" do |f| %>
    <%= label_tag "subject", t("questions.choice_subject"), class: "col-md-4" %>
    <div class="select-subject col-md-8">
      <%= select_tag("subject", options_for_select(subject_options(@subjects)), {class:"form-control button"}) %>
    </div>
    <%= label_tag "file", t("questions.choice_file"), class: "col-md-4" %>
    <div class="file col-md-8">
      <%= file_field_tag :file, class: "form-control" %>
    </div>
    <%= f.submit t("questions.create_list"), class:"btn btn-primary button" %>
  <% end %>
</div>
<hr>

<div>
  <h2><%= t "questions.file_format" %></h2>
  <div>
    <%= t "questions.file_format_instruction_html" %>
  </div>
</div>