config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "sessions#new"
    as :user do
      get "/signup", to: "devise/sessions#new"
      post "/signup", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
    end
    scope module: :supervisor do
      resources :questions
      as :questions do
        get "/new_list_questions", to: "questions#new_list"
        post "/create_list_questions", to: "questions#create_list"
      end
      resources :exams
      resources :trainees do
        resources :user_exams
      end
      resources :users do
        collection do
          get "/trainees", to: "users#trainees_index"
          get "/supervisors", to: "users#supervisors_index"
        end
      end
    end
    scope module: :trainee do
      resources :user_exams
    end
    devise_for :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable
  enum role: {supervisor: 1, trainee: 2}
  attr_accessor :remember_token
  before_save ->{email.downcase!}
  validates :name, presence: true,
            length: {maximum: Settings.user.name.max_length}
  validates :email, presence: true, uniqueness: true,
            length: {maximum: Settings.user.email.max_length},
            format: {with: Settings.user.email.regex}
  validates :password, presence: true,
            length: {minimum: Settings.user.password.min_length}
  has_many :user_exams, dependent: :destroy
  scope :sort_by_created_at_desc, ->{order created_at: :desc}

  def remember
    self.remember_token = User.new_token
    update_column :remember_digest, User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false unless digest

    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_column :remember_digest, nil
  end

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create(string, cost: cost)
    end
  end
end

app/controllers/supervisor/exams_controller.rb
class Supervisor::ExamsController < SupervisorController
  before_action :load_exam, only: :show
  load_and_authorize_resource

  def index
    @q = Exam.ransack(params[:q])
    @exams = @q.result.includes(:subject)
               .paginate(page: params[:page]).per_page(Settings.page)
  end

  def show
    @questions = Exam.questions_sort_by_created_at_asc(@exam).includes(:answers)
  end

  private

  def load_exam
    @exam = Exam.find_by(id: params[:id])
    return if @exam

    flash[:danger] = t("exams.not_found!")
    redirect_back(fallback_location: supervisor_exams_path)
  end
end

app/controllers/supervisor/questions_controller.rb
class Supervisor::QuestionsController < SupervisorController
  before_action :load_subject, :load_file_param, :correct_file_type,
                only: :create_list
  load_and_authorize_resource

  def index
    @questions = @questions.sort_by_created_at_desc
                           .paginate(page: params[:page])
                           .per_page(Settings.page)
  end

  def new_list
    @subjects = Subject.sort_by_created_at_desc
  end

  def create_list
    FileService.read_questions_from_file!(@file_path, @subject)
    flash[:success] = t "questions.create_list_success"
    redirect_to questions_path
  rescue ActiveRecord::ActiveRecordError
    flash[:danger] = t "questions.create_list_fail"
    redirect_to new_list_questions_path
  end

  private

  def load_subject
    @subject = Subject.find_by id: params[:subject].to_i
    return if @subject

    flash[:danger] = t "questions.choice_subject!"
    redirect_to new_list_questions_path
  end

  def load_file_param
    @file_param = params["file"]
    return if @file_param

    flash[:danger] = t "questions.please_choice_file!"
    redirect_to new_list_questions_path
  end

  def correct_file_type
    @file_path = @file_param.tempfile.to_path.to_s
    return if @file_path.end_with?(".xlsx") || @file_path.end_with?(".xls")

    flash[:danger] = t "questions.please_choice_correct_file_type!"
    redirect_to new_list_questions_path
  end
end

app/controllers/supervisor/user_exams_controller.rb
class Supervisor::UserExamsController < SupervisorController
  before_action :load_trainee, only: :index
  authorize_resource

  def index
    @user_exams = @trainee.user_exams
                          .sort_by_created_at_desc
                          .includes({exam: :exam_questions}, :subject)
                          .paginate(page: params[:page])
                          .per_page(Settings.page)
  end

  private

  def load_trainee
    @trainee = User.find_by id: params[:trainee_id]
    return if @trainee

    flash[:danger] = t "trainees.not_found!"
    redirect_to root_path
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < SupervisorController
  authorize_resource

  def trainees_index
    @q = User.ransack(params[:q])
    @trainees = @q.result.trainee.sort_by_created_at_desc
                  .includes(:user_exams)
                  .page(params[:page]).per_page(Settings.page)
  end

  def supervisors_index
    @q = User.ransack(params[:q])
    @supervisors = @q.result.supervisor.sort_by_created_at_desc
                     .page(params[:page]).per_page(Settings.page)
  end
end

app/controllers/supervisor_controller.rb
class SupervisorController < ApplicationController
  before_action :authenticate_user!

  private

  def current_ability
    @current_ability ||=
      Ability.new(current_user, Settings.namespace.supervisor)
  end
end

app/views/supervisor/users/_supervisor.html.erb
<tr>
  <td class="name"><%= supervisor.name %></td>
  <td class="create_date"><%= l(supervisor.created_at, format: :long) %></td>
  <td class="profile">
    <%= link_to(user_path(supervisor)) do %>
      <i class="glyphicon glyphicon-user"></i>
    <% end %>
  </td>
  <td class="edit">
    <%= link_to(edit_user_path(supervisor)) do %>
      <i class="glyphicon glyphicon-edit"></i>
    <% end %>
  </td>
  <td class="delete">
    <%= link_to(user_path(supervisor), method: :delete) do %>
      <i class="glyphicon glyphicon-trash"></i>
    <% end %>
  </td>
</tr>

app/views/supervisor/users/_trainee.html.erb
<tr>
  <td class="name"><%= trainee.name %></td>
  <td class="create_date"><%= l(trainee.created_at, format: :long) %></td>
  <td class="exams_count"><%= trainee.user_exams.size %></td>
  <td class="exams">
    <%= link_to(trainee_user_exams_path(trainee_id: trainee.id)) do %>
      <i class="glyphicon glyphicon-list-alt"></i>
    <% end %>
  </td>
  <td class="profile">
    <%= link_to(user_path(trainee)) do %>
      <i class="glyphicon glyphicon-user"></i>
    <% end %>
  </td>
  <td class="edit">
    <%= link_to(edit_user_path(trainee)) do %>
      <i class="glyphicon glyphicon-edit"></i>
    <% end %>
  </td>
  <td class="delete">
    <%= link_to(user_path(trainee), method: :delete) do %>
      <i class="glyphicon glyphicon-trash"></i>
    <% end %>
  </td>
</tr>

app/views/supervisor/users/supervisors_index.html.erb
<% provide :title, t("users.titles.supervisors") %>

<div class="users-container">
  <div class="tabcontent supervisor-content">
    <div class="row">
      <h2><%= t("users.supervisors") %></h2>
      <%= search_form_for @q, url: supervisors_users_path, class: "input-group search-box" do |f| %>
        <%= f.text_field :name_cont, class: "form-control", placeholder: t("users.search_for") %>
        <span class="input-group-btn">
          <%= f.submit t("users.search"), class: "btn btn-default" %>
        </span>
      <% end %>
    </div>
    <table class="supervisor-table table">
      <thead>
        <tr>
          <th class="name"><%= t("users.name") %></th>
          <th class="create_date"><%= t("users.create_date") %></th>
          <th class="profile"><%= t("users.porfile") %></th>
          <th class="edit"><%= t("users.edit") %></th>
          <th class="delete"><%= t("users.delete") %></th>
        </tr>
      </thead>
      <tbody id="supervisors">
        <%= render partial: "supervisor", collection: @supervisors, as: :supervisor %>
      </tbody>
    </table>
    <div class="pagination-container" id="supervisor-pagination">
      <%= paginate @supervisors, remote: true, theme: "twitter-bootstrap-3" %>
    </div>
  </div>
</div>

app/views/supervisor/users/supervisors_index.js.erb
$("#supervisors").html("<%= j render(partial: 'supervisor', collection: @supervisors, as: :supervisor) %>");
$("#supervisor-pagination").html("<%= j paginate(@supervisors, remote: true, theme: 'twitter-bootstrap-3') %>");

app/views/supervisor/users/trainees_index.html.erb
<% provide :title, t("users.titles.trainees") %>

<div class="users-container">
  <div class="tabcontent trainee-content">
    <div class="row">
      <h2><%= t("users.trainees") %></h2>
      <%= search_form_for @q, url: trainees_users_path, class: "input-group search-box" do |f| %>
        <%= f.text_field :name_cont, class: "form-control", placeholder: t("users.search_for") %>
        <span class="input-group-btn">
          <%= f.submit t("users.search"), class: "btn btn-default" %>
        </span>
      <% end %>
    </div>
    <table class="trainee-table table">
      <thead>
        <tr>
          <th class="name"><%= t("users.name") %></th>
          <th class="create_date"><%= t("users.create_date") %></th>
          <th class="exams_count"><%= t("users.exams_count") %></th>
          <th class="exams"><%= t("users.exams") %></th>
          <th class="profile"><%= t("users.porfile") %></th>
          <th class="edit"><%= t("users.edit") %></th>
          <th class="delete"><%= t("users.delete") %></th>
        </tr>
      </thead>
      <tbody id="trainees">
        <%= render partial: "trainee", collection: @trainees, as: :trainee %>
      </tbody>
    </table>
    <div class="pagination-container" id="trainee-pagination">
      <%= paginate @trainees, remote: true, theme: "twitter-bootstrap-3" %>
    </div>
  </div>
</div>

app/views/supervisor/users/trainees_index.js.erb
$("#trainees").html("<%= j render(partial: 'trainee', collection: @trainees, as: :trainee) %>");
$("#trainee-pagination").html("<%= j paginate(@trainees, remote: true, theme: 'twitter-bootstrap-3') %>");