config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "sessions#new"
    as :user do
      get "/signup", to: "devise/sessions#new"
      post "/signup", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
    end
    scope module: :supervisor do
      resources :questions
      as :questions do
        get "/new_list_questions", to: "questions#new_list"
        post "/create_list_questions", to: "questions#create_list"
      end
      resources :exams
      resources :trainees do
        resources :user_exams
      end
      resources :users do
        collection do
          get "/trainees", to: "users#trainees_index"
          get "/supervisors", to: "users#supervisors_index"
        end
      end
    end
    scope module: :trainee do
      resources :user_exams
    end
    devise_for :users
  end
end

app/views/layouts/_dashboard.html.erb
<%= javascript_pack_tag "sidebar_active" %>
<ul class="nav navbar-fixed-left">
  <li class="nav-item"><%= link_to t("user"), "#" %>
    <ul class="user-nav">
      <li class="nav-item sub-item"><%= link_to t("new_user"), new_user_path %></li>
      <li class="nav-item sub-item"><%= link_to t("trainee"), trainees_users_path %></li>
      <li class="nav-item sub-item"><%= link_to t("supervisor"), supervisors_users_path %></li>
    </ul>
  </li>
  <li class="nav-item"><%= link_to t("question"), questions_path %></li>
  <li class="nav-item"><%= link_to t("exam"), exams_path %></li>
  <li class="nav-item"><%= link_to t("subject"), "#" %></li>
</ul>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="header-container">
    <%= link_to t("header.test_system"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to image_tag("american.jpg", class: "local_image"), locale: :en %>
        </li>
        <li>
          <%= link_to image_tag("vietnam.jpg", class: "local_image"), locale: :vi %>
        </li>
        <li><%= link_to t("header.home"), "#" %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to t("header.profile"), "#" %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to t("header.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("header.login"), signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript">
      var LOCALE = "<%= I18n.locale %>";
    </script>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= raw custom_bootstrap_flash %>
    <%= render "layouts/header" %>
    <% if user_signed_in? %>
      <% if current_user.supervisor? %>
        <div id="dashboard">
          <%= render "layouts/dashboard" %>
        </div>
        <div id="content">
          <%= yield %>
        </div>
      <% elsif %>
        <div class="container">
          <%= yield %>
        </div>
      <% end %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>